version: "3.9"
services:
  postgres:
      container_name: pg-database
      image: postgres:13
      environment:
        POSTGRES_DB: "ny_taxi"
        POSTGRES_USER: "root"
        POSTGRES_PASSWORD: "root"
      volumes:
        - /home/timur/ZOOMCAMP/ny_taxi_postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - pg-network
  pgadmin:
      container_name: pgadmin-2
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "root"
      ports:
        - "8080:80"
      networks:
        - pg-network
networks:
  pg-network:
    driver: bridge